darknet3d_node:
  ros__parameters:
    darknet_ros_topic: /darknet_ros/bounding_boxes
    output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
    point_cloud_topic: /kinect2/hd/points
    working_frame: kinect2_link
    maximum_detection_threshold: 0.1
    minimum_probability: 0.4
    interested_classes: ["bottle", "vase", "cup"]
